export const GET_MACHINE_SUCCESS = 'GET_MACHINE_SUCCESS';
export const ADD_CARD = 'ADD_CARD';
export const ADD_LIST = 'ADD_LIST';
export const DRAG_HAPPENDED = 'DRAG_HAPPENDED';
export const EDIT_CARD = "EDIT_CARD";
export const DELETE_CARD = "DELETE_CARD";
export const EDIT_LIST_TITLE = "EDIT_LIST_TITLE";
export const DELETE_LIST = "DELETE_LIST";

export const FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';